server:
  port: 9703
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.7.29:3306/es-project?useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # \u53EA\u5BF9\u6570\u636E\u5E93\u7684\u8868\u8FDB\u884C\u9A8C\u8BC1,\u4E0D\u4F1A\u81EA\u52A8\u589E\u5220\u5B57\u6BB5/\u8868\u7B49


logging:
  level:
    org:
      hibernate:
        # \u8BBE\u7F6Eorg.hibernate.SQL\u7684\u65E5\u5FD7\u7EA7\u522B\u4E3Adebug,\u56E0\u4E3Ashow-sql\u8981\u663E\u793A\u65E5\u5FD7
        SQL: debug
security:
  basic:
    enabled: false